submodules:
    include: all

build:
    image: latest

python:
    setup_py_install: true
    install:
        - requirements: requirements.txt
        - method: pip
        - path: .
        - method: setuptools