function Hd = bpf_vitalsign
% bpf_vitalsign 生命体征带通 IIR 滤波器（巴特沃斯）
% 返回一个可直接用于 filter(Hd, x) 的离散时间滤波器对象。
%
% 设计目标：
%   - 类型：IIR 巴特沃斯带通
%   - 采样率：Fs = 20 Hz（与生命体征时间序列的采样率一致）
%   - 半功率(-3 dB)截止频率：Fc1 = 0.1 Hz，Fc2 = 2 Hz
%   - 阶数：N = 4（总阶数为 4，对应两个二阶节）
%
% 使用示例：
%   Hd = bpf_vitalsign();
%   y  = filter(Hd, x);          % 因果滤波（有群时延）
%   % 若希望零相位响应（离线）：建议改用“等价实现”中的 designfilt 版本配合 filtfilt
%
% 备注：
%   本函数使用了较老的 fdesign 接口。新项目更建议采用 designfilt。

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 09-May-2021 12:24:57

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% 所有频率单位为 Hz
Fs = 20;   % 生命体征序列采样率（例如 Tf = 0.05 s -> Fs = 20 Hz）

% 设计参数
N   = 4;    % 滤波器总阶数（巴特沃斯）
Fc1 = 0.1;  % 下截止(-3 dB)频率（呼吸低端）
Fc2 = 2;    % 上截止(-3 dB)频率（心跳高端）

% 构建 fdesign 对象，并按巴特沃斯方法设计
% 规格 'N,F3dB1,F3dB2' 表示给定总阶数和两个半功率截止频率
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');  % 返回 dfilt 滤波器对象

% [EOF]


% %%等价实现 1（推荐）：使用 designfilt 返回 digitalFilter 对象
% function Hd = bpf_vitalsign_designfilt
% % 现代写法，返回 digitalFilter 对象（带 SOSMatrix/ScaleValues）
% 
% Fs  = 20;
% N   = 4;         % 总阶数=4（两个 biquad）
% Fc1 = 0.1;
% Fc2 = 2.0;
% 
% Hd = designfilt('bandpassiir', ...
%     'FilterOrder',        N, ...
%     'HalfPowerFrequency1',Fc1, ...
%     'HalfPowerFrequency2',Fc2, ...
%     'SampleRate',         Fs, ...
%     'DesignMethod',       'butter');
% 
% % 使用：
% %   y_causal   = filtfilt(Hd, x);            % R2024a 起支持 digitalFilter 直接 filtfilt
% %   % 若版本较旧，可用：
% %   % y_zero = filtfilt(Hd.Coefficients.SOSMatrix, Hd.Coefficients.ScaleValues, x);
% 
% end



% %%等价实现 2：直接用 butter 得到 [b,a] 系数
% function [b, a, Fs] = bpf_vitalsign_ba
% % 返回可用于 filter/filtfilt 的 [b,a] 系数
% 
% Fs  = 20;
% N_total = 4;                 % 期望的总阶数
% Nbp = N_total / 2;           % butter 的带通指定“原型阶数”，带通总阶数=2*Nbp=4
% 
% Fc1 = 0.1;
% Fc2 = 2.0;
% Wn  = [Fc1 Fc2] / (Fs/2);    % 归一化截止到 Nyquist
% 
% [b, a] = butter(Nbp, Wn, 'bandpass');
% 
% % 使用：
% %   y_causal = filter(b, a, x);          % 因果
% %   y_zero   = filtfilt(b, a, x);        % 零相位（离线推荐）
% end